//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Solutions
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int id { get; set; }
        public Nullable<int> AccountNo { get; set; }
        public Nullable<double> Amount { get; set; }
        public string TransType { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
    }
}
